### PR TITLE
Capacitor merge

### PR DESCRIPTION
**Pull request by darcyadams**
*This PR has breaking changes*

Finally getting around to merging in al the great work done by @tommoor on his capacitor fork. 

- createStore now creates a single store object, doesn't act as a factory. As flux standards!
- store contents is no longer mixed in with methods, now in state object
- You no longer need to do MyStore.store.myMethod, instead you can use MyStore.myMethod
- Defines default getState and get methods

anyone using `scheme` will be impacted the most by these changes, but those relying solely on their own `getState` methods will be largely unaffected.

### CODE REVIEW

**Comment by darcyadams** [comment]
@tommoor any other reservations about merging this into delorean? IMO, these changes are needed (and perhaps a few other large ones) before we go to 1.0

**Comment by darcyadams** [comment]
I'm have tested this PR pretty thoroughly on a large application, in the absence of @f I'm going to go ahead and merge this.

**Comment by tommoor** [comment]
Hey @darcyadams - apologies, I've been on holiday for the last week. Excited to see these changes merged back in, it means we can continue to use the main project and I'll contribute more ideas. :smile:

**Comment by tommoor** [comment]
@darcyadams FYI: looks like you merged in my README changes, those'll want reverting.

**Comment by darcyadams** [comment]
@tommoor yes, in my mind your changes were a must have before we go 1.0, thank you for sharing your implementation, saved me a lot of work :smile: 

Good catch o the readme, reverted.

**Comment by f** [comment]
You guys are working great on DeLorean! Thank you so much! :+1:

I'll be back on July 19

**Pull request merged**
