### PR TITLE
Cleanup unused events after a dispatched action is handled by the store

### PR DESCRIPTION
**Pull request by darcyadams**
This PR does the following...
- Allows the action handler to `emit` a `rollback` event, which will reject the promise returned to the `dispatch` method. This allows the developer to use a `catch` error handler in addition to a `then` handler.
- After an action handler has run, cleanup the bound events to prevent memory leaks.
- set the `defaultMaxListeners` to 50. This is a somewhat arbitrary number. I certainly feel like 10 (the built-in default max) is too low. My app goes over 10 quite frequently. Since we auto cleanup these events now, I want to make sure there is plenty of headroom.

### CODE REVIEW

**Comment by tommoor** [comment]
I like it, no timers necessary!

**Comment by darcyadams** [comment]
yeah :smile: timer would have been a last resort.

**Comment by darcyadams** [comment]
@f any input on this? or am I okay to merge?

**Comment by darcyadams** [comment]
I have been running this branch in my app for over a week w/ no issues. merging.

**Comment by tommoor** [comment]
same, been running in production for a week :smile: thanks!

**Pull request merged**
